INSERT INTO USERS(name, email, password, created_at, updated_at, role, enabled)
VALUES ('admin', 'toto@gmail.com', '$2a$10$Pu82bKudIeT4VWJWbthEReOyKsz6SJj6aFuuYt0iNBn6kJUeViPci', '2012/12/02',
        '2014/12/02', 'ADMIN', 1),
       ('test TEST', 'test@test.com', '$2a$10$2Ypxvjh8x/hM2MIRfrI7F./VShkFQjvkjEdWax4UG2/S3bRfZ1cRe', '2012/12/02',
        '2014/12/02', 'USER', 1);

INSERT INTO RENTALS(name,
                    surface,
                    price,
                    picture,
                    description,
                    owner_id,
                    created_at,
                    updated_at)
VALUES ('test house 1',
        432,
        300,
        'https://blog.technavio.org/wp-content/uploads/2018/12/Online-House-Rental-Sites.jpg',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a lectus eleifend, varius massa ac, mollis tortor. Quisque ipsum nulla, faucibus ac metus a, eleifend efficitur augue. Integer vel pulvinar ipsum. Praesent mollis neque sed sagittis ultricies. Suspendisse congue ligula at justo molestie, eget cursus nulla tincidunt. Pellentesque elementum rhoncus arcu, viverra gravida turpis mattis in. Maecenas tempor elementum lorem vel ultricies. Nam tempus laoreet eros, et viverra libero tincidunt a. Nunc vel nisi vulputate, sodales massa eu, varius erat.',
        1,
        '2012/12/02',
        '2014/12/02'),
       ('test house 2',
        154,
        200,
        'https://blog.technavio.org/wp-content/uploads/2018/12/Online-House-Rental-Sites.jpg',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a lectus eleifend, varius massa ac, mollis tortor. Quisque ipsum nulla, faucibus ac metus a, eleifend efficitur augue. Integer vel pulvinar ipsum. Praesent mollis neque sed sagittis ultricies. Suspendisse congue ligula at justo molestie, eget cursus nulla tincidunt. Pellentesque elementum rhoncus arcu, viverra gravida turpis mattis in. Maecenas tempor elementum lorem vel ultricies. Nam tempus laoreet eros, et viverra libero tincidunt a. Nunc vel nisi vulputate, sodales massa eu, varius erat.',
        2,
        '2012/12/02',
        '2014/12/02'),
       ('test house 3',
        234,
        100,
        'https://blog.technavio.org/wp-content/uploads/2018/12/Online-House-Rental-Sites.jpg',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a lectus eleifend, varius massa ac, mollis tortor. Quisque ipsum nulla, faucibus ac metus a, eleifend efficitur augue. Integer vel pulvinar ipsum. Praesent mollis neque sed sagittis ultricies. Suspendisse congue ligula at justo molestie, eget cursus nulla tincidunt. Pellentesque elementum rhoncus arcu, viverra gravida turpis mattis in. Maecenas tempor elementum lorem vel ultricies. Nam tempus laoreet eros, et viverra libero tincidunt a. Nunc vel nisi vulputate, sodales massa eu, varius erat.',
        1,
        '2012/12/02',
        '2014/12/02');
