spring:
  application:
    name: estate
  datasource:
    url: jdbc:mysql://localhost:3306/ESTATE
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db\script.sql
      continue-on-error: false
      data-locations: classpath:db\data.sql
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
estate:
  jwt:
    expiration: 86400000
logging:
  level:
    org:
      springframework: INFO
    com:
      estate: DEBUG
server:
  port: 3001
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  #    enabled: false // disable swagger-ui endpointd
  # /api-docs endpoint custom path
  api-docs:
    path: /api-docs
#    enabled: false // disable api-docs endpoint
