spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
            client-authentication-method: none
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/github/code"
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db\script.sql
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
