spring:
  application:
    name: estate
  datasource:
    url: jdbc:mysql://localhost:3306/ESTATE
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db\script.sql
      continue-on-error: false
      data-locations: classpath:db\data.sql
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
estate:
  jwt:
    expiration: 86400000
server:
  port: 3001
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true  #disable swagger-ui endpoint with false value
  # /api-docs endpoint custom path
  api-docs:
    path: /api/v1/docs
    enabled: true # disable api-docs endpoint with false value
  show-oauth2-endpoint: true
  show-login-endpoint: true
logging:
  level:
    org:
      springframework: INFO
    com:
      estate: DEBUG
  config: classpath:logback-spring.xml

